"""Priority

Revision ID: c1455ca7e59f
Revises: 40b0a5a8a02b
Create Date: 2024-04-20 16:11:31.537686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1455ca7e59f'
down_revision = '40b0a5a8a02b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting_priority', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting_priority', schema=None) as batch_op:
        batch_op.drop_column('priority')

    # ### end Alembic commands ###
